package entity

import "time"

// ---------------------------------------------------------------------------
// Journal -- append-only fact store for agent memory (PERS-03, PERS-05)
// ---------------------------------------------------------------------------

// JournalEntry is a single persisted note in the agent's journal for a user.
// Journal entries are append-only -- there is no update or delete method.
type JournalEntry struct {
	ID             string    // Generated by the store plugin on AppendJournal
	TenantID       TenantID
	UserID         UserID         // Always the user who authored the fact
	ChatID         ChatID         // Non-empty = chat-scoped entry; empty = user-level
	ConversationID ConversationID // Conversation that produced this entry (empty = unbound)
	Category       string         // One of: "Key Events", "Decisions", "TODOs", "Preferences", "Open Questions", "Plans"
	Content        string         // The fact or note text
	MessageID      string         // references messages.id, empty = unlinked
	CreatedAt      time.Time
}

// JournalFilter specifies retrieval criteria for GetJournal queries.
// All fields are optional. Zero value means "no filter on this field".
type JournalFilter struct {
	// UserID: when non-empty, scopes results to a single user.
	// When empty, returns entries from all users (scoped by tenant + other filters).
	UserID UserID
	// ChatID: when non-empty, scopes results to a specific chat.
	ChatID ChatID
	// ConversationID: when non-empty, filters entries to this conversation.
	ConversationID ConversationID
	// Categories: when non-empty, restricts to entries in these categories.
	Categories []string
	// Query: when non-empty, performs FTS5 full-text search on the Content field.
	Query string
	// BeforeTime: when non-zero, filters entries with created_at < BeforeTime.
	BeforeTime time.Time
}
