#!/usr/bin/env bash
set -uo pipefail

# Build plugin .so files from pkg/plugins/ and pkg/plugins-*/ directories.
#
# Usage:
#   ./scripts/build-plugins.sh              # build all plugins
#   ./scripts/build-plugins.sh channel/telegram  # build one plugin

export CGO_ENABLED=1

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODULE_PATH="$(head -1 "$REPO_ROOT/go.mod" | awk '{print $2}')"
BIN_DIR="$REPO_ROOT/bin"

# Track _build dirs for cleanup
BUILD_DIRS=()

cleanup() {
    for d in "${BUILD_DIRS[@]}"; do
        rm -rf "$d"
    done
}
trap cleanup EXIT

mkdir -p "$BIN_DIR"

FAILURES=()
SUCCESSES=()

build_plugin() {
    local plugin_dir="$1"   # absolute path e.g. /repo/pkg/plugins/channel/telegram
    local rel_path="$2"     # relative to repo root e.g. pkg/plugins/channel/telegram
    local output_name="$3"  # e.g. channel_telegram

    # Derive import path
    local import_path="${MODULE_PATH}/${rel_path}"
    local so_file="${BIN_DIR}/plugins/${output_name}.so"

    # Create _build wrapper inside plugin dir (Go ignores _ prefixed dirs)
    local build_dir="${plugin_dir}/_build"
    mkdir -p "$build_dir"
    BUILD_DIRS+=("$build_dir")

    cat > "$build_dir/main.go" <<GOEOF
// Code generated by build-plugins.sh; DO NOT EDIT.
package main

import (
	p "${import_path}"
	"${MODULE_PATH}/internal/domain/port"
)

func Manifest() port.PluginManifest { return p.Manifest() }
func NewPlugin() port.Plugin        { return p.NewPlugin() }
GOEOF

    # Build
    if ! go build -buildmode=plugin -o "$so_file" "$build_dir" 2>&1; then
        echo "FAILED: ${rel_path}"
        FAILURES+=("$rel_path")
        rm -rf "$build_dir"
        return 1
    fi

    # Verify symbols (capture once; use bash pattern match to avoid SIGPIPE with pipefail)
    local nm_output
    nm_output="$(go tool nm "$so_file" 2>/dev/null || true)"

    local missing=0
    if [[ "$nm_output" != *NewPlugin* ]]; then
        echo "FAILED: ${rel_path} -- missing NewPlugin symbol"
        missing=1
    fi
    if [[ "$nm_output" != *Manifest* ]]; then
        echo "FAILED: ${rel_path} -- missing Manifest symbol"
        missing=1
    fi

    if [ "$missing" -ne 0 ]; then
        FAILURES+=("$rel_path")
        rm -rf "$build_dir"
        return 1
    fi

    # Clean up _build dir immediately on success
    rm -rf "$build_dir"
    echo "OK: ${rel_path} -> ${output_name}.so"
    SUCCESSES+=("$rel_path")
    return 0
}

# Discover and build plugins
build_all() {
    local filter="${1:-}"

    for root in "$REPO_ROOT"/pkg/plugins "$REPO_ROOT"/pkg/plugins-*; do
        [ -d "$root" ] || continue
        local root_base
        root_base="$(basename "$root")"

        for plugin_dir in "$root"/*/*; do
            [ -d "$plugin_dir" ] || continue

            # Extract kind/name (depth 2 under root)
            local name
            name="$(basename "$plugin_dir")"
            local kind
            kind="$(basename "$(dirname "$plugin_dir")")"
            local kind_name="${kind}/${name}"

            # If filter specified, only build matching plugin
            if [ -n "$filter" ] && [ "$kind_name" != "$filter" ]; then
                continue
            fi

            # Determine output name
            local output_name
            local rel_path
            case "$root_base" in
                plugins)
                    output_name="${kind}-${name}"
                    rel_path="pkg/plugins/${kind}/${name}"
                    ;;
                plugins-*)
                    local suffix="${root_base#plugins-}"
                    output_name="${suffix}-${kind}-${name}"
                    rel_path="pkg/${root_base}/${kind}/${name}"
                    ;;
            esac

            build_plugin "$plugin_dir" "$rel_path" "$output_name"
        done
    done
}

build_all "$@"

# Summary
echo ""
echo "--- Build Summary ---"
echo "OK:     ${#SUCCESSES[@]}"
echo "FAILED: ${#FAILURES[@]}"

if [ ${#FAILURES[@]} -gt 0 ]; then
    echo ""
    echo "Failed plugins:"
    for f in "${FAILURES[@]}"; do
        echo "  - $f"
    done
    exit 1
fi
